# Generated by Django 4.0.3 on 2022-03-25 11:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='explanation',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
