# Generated by Django 4.0.3 on 2022-03-28 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_comment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingbasket',
            options={'ordering': ['buyer']},
        ),
        migrations.RenameField(
            model_name='shoppingbasket',
            old_name='buyyer',
            new_name='buyer',
        ),
    ]
